/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProveedoresRouteImport } from './routes/app/proveedores'
import { Route as AppProductosRouteImport } from './routes/app/productos'
import { Route as AppFacturasRouteImport } from './routes/app/facturas'
import { Route as AppClientesRouteImport } from './routes/app/clientes'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProveedoresRoute = AppProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductosRoute = AppProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFacturasRoute = AppFacturasRouteImport.update({
  id: '/facturas',
  path: '/facturas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/productos': typeof AppProductosRoute
  '/app/proveedores': typeof AppProveedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/productos': typeof AppProductosRoute
  '/app/proveedores': typeof AppProveedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/clientes': typeof AppClientesRoute
  '/app/facturas': typeof AppFacturasRoute
  '/app/productos': typeof AppProductosRoute
  '/app/proveedores': typeof AppProveedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/clientes'
    | '/app/facturas'
    | '/app/productos'
    | '/app/proveedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/clientes'
    | '/app/facturas'
    | '/app/productos'
    | '/app/proveedores'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/clientes'
    | '/app/facturas'
    | '/app/productos'
    | '/app/proveedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/proveedores': {
      id: '/app/proveedores'
      path: '/proveedores'
      fullPath: '/app/proveedores'
      preLoaderRoute: typeof AppProveedoresRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/productos': {
      id: '/app/productos'
      path: '/productos'
      fullPath: '/app/productos'
      preLoaderRoute: typeof AppProductosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/facturas': {
      id: '/app/facturas'
      path: '/facturas'
      fullPath: '/app/facturas'
      preLoaderRoute: typeof AppFacturasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppClientesRoute: typeof AppClientesRoute
  AppFacturasRoute: typeof AppFacturasRoute
  AppProductosRoute: typeof AppProductosRoute
  AppProveedoresRoute: typeof AppProveedoresRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppClientesRoute: AppClientesRoute,
  AppFacturasRoute: AppFacturasRoute,
  AppProductosRoute: AppProductosRoute,
  AppProveedoresRoute: AppProveedoresRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
